### ISSUE TITLE
请问ins_camera::GyroData 的单位是什么？以及坐标系是什么样子的？

### ISSUE THREAD

**Issue by lmz-whu** [Insta360Develop/CameraSDK-Cpp#18]
文档里只是简短的介绍了ins_camera::GyroData的字段，请问这些字段的但是是什么？以及坐标系是什么样子的？谢谢

int64_t | timestamp
double | ax
double | ay
double | az
double | gx
double | gy
double | gz

**Comment by lmz-whu** [comment]
我自己来回答一下吧，ax,ay,az的单位是g，gx,gy,gz的单位是rad/s
坐标系和realsense的IMU坐标系一致

**Comment by dzvoid** [comment]
请问下 OnAudioData， OnVideoData，OnGyroData，OnExposureData 这4个函数如何使用啊？ 怎么获取到需要的数据呢？

**Comment by Ben93kie** [comment]
Was wondering the same thing about OnGyroData (sorry, only English).

**Comment by dzvoid** [comment]
> Was wondering the same thing about OnGyroData (sorry, only English).

Thank you very much!
