### ISSUE TITLE
no device found error

### ISSUE THREAD

**Issue by ohDDo** [Insta360Develop/CameraSDK-Cpp#39]
env : linux(ubuntu 20.04), insta360 x3

I already followed all the **prerequisite** steps.
output of lsusb:
`Bus 001 Device 010: ID 2e1a:xxxx Arashi Vision Insta360 X3
`

I run the **main.cc** and got the _no device found massage_

How can I do to find the device?

**Comment by Gaaaavin** [comment]
Same problem here!
